// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as TriggerNlpAnalysisProcedure from "../trigger_nlp_analysis_procedure";

export type TriggerNlpAnalysisArgs = __Infer<typeof TriggerNlpAnalysisProcedure.params>;
export type TriggerNlpAnalysisResult = __Infer<typeof TriggerNlpAnalysisProcedure.returnType>;

