// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import FinalizeInferenceReducer from "../finalize_inference_reducer";
import IngestNewsArticleReducer from "../ingest_news_article_reducer";
import OverrideClassificationReducer from "../override_classification_reducer";
import SeedUserReducer from "../seed_user_reducer";

export type FinalizeInferenceParams = __Infer<typeof FinalizeInferenceReducer>;
export type IngestNewsArticleParams = __Infer<typeof IngestNewsArticleReducer>;
export type OverrideClassificationParams = __Infer<typeof OverrideClassificationReducer>;
export type SeedUserParams = __Infer<typeof SeedUserReducer>;

