// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  articleId: __t.u64().name("article_id"),
  isProcessed: __t.bool().name("is_processed"),
  classification: __t.string(),
  confidenceScore: __t.f32().name("confidence_score"),
  modelVersion: __t.string().name("model_version"),
  flaggedByNewsguard: __t.bool().name("flagged_by_newsguard"),
});
