// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArticleMetadata = __t.object("ArticleMetadata", {
  id: __t.u64(),
  sourceUrl: __t.string(),
  domain: __t.string(),
  headline: __t.string(),
  publishedAt: __t.timestamp(),
  ingestedAt: __t.timestamp(),
});
export type ArticleMetadata = __Infer<typeof ArticleMetadata>;

export const DetectionInference = __t.object("DetectionInference", {
  articleId: __t.u64(),
  isProcessed: __t.bool(),
  classification: __t.string(),
  confidenceScore: __t.f32(),
  modelVersion: __t.string(),
  flaggedByNewsguard: __t.bool(),
});
export type DetectionInference = __Infer<typeof DetectionInference>;

export const SystemUser = __t.object("SystemUser", {
  identity: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type SystemUser = __Infer<typeof SystemUser>;

